api_providers:
  openai:
    models:
      gpt-4o:
        input_price: 2.50
        output_price: 10.00
      gpt-4o-mini:
        input_price: 0.150
        output_price: 0.600
      gpt-4-turbo:
        input_price: 10.00
        output_price: 30.00
      gpt-4:
        input_price: 30.00
        output_price: 60.00
      gpt-3.5-turbo:
        input_price: 0.50
        output_price: 1.50
default_model: "openai/gpt-4o-mini"
